# Generated by Django 4.0.1 on 2022-01-31 23:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nome compeleto')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(max_length=300, verbose_name='Data de Nascimento')),
                ('document', models.ImageField(blank=True, upload_to='', verbose_name='Foto documento de identificação')),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, max_length=14, verbose_name='CPF do responsável')),
                ('mother_name', models.CharField(max_length=300, verbose_name='Nome da Mãe')),
                ('address', models.CharField(max_length=500, verbose_name='Endereço Completo')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='Última turma de catequese')),
                ('last_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2022)], verbose_name='Último ano na catequese')),
                ('baptized', models.BooleanField(default=False, verbose_name='Já foi Batizado')),
                ('eucharisted', models.BooleanField(default=False, verbose_name='Recebeu Eucaristia')),
                ('baptism', models.ImageField(blank=True, upload_to='', verbose_name='Foto Lembrança do Batismo')),
                ('eucharist', models.ImageField(blank=True, upload_to='', verbose_name='Foto Lembrança da Eucaristia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
