# Generated by Django 4.0.1 on 2022-02-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='baptism',
            field=models.ImageField(blank=True, upload_to='documents/', verbose_name='Foto Lembrança do Batismo'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='document',
            field=models.ImageField(blank=True, upload_to='documents/', verbose_name='Foto documento de identificação'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='eucharist',
            field=models.ImageField(blank=True, upload_to='documents/', verbose_name='Foto Lembrança da Eucaristia'),
        ),
    ]
