# Generated by Django 4.0.1 on 2022-02-01 13:53

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_alter_matricula_baptism_alter_matricula_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF do responsável')),
                ('proof', models.FileField(upload_to='proofs/', verbose_name='Comprovante de Pagamento')),
            ],
        ),
    ]
