# Generated by Django 4.0.1 on 2022-02-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_proof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proof',
            options={'verbose_name': 'Comprovante', 'verbose_name_plural': 'Comprovantes'},
        ),
    ]
