# Generated by Django 4.0.1 on 2022-03-11 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def load_data(apps, schema_editor):
        Nivel = apps.get_model("matricula", "Nivel")
        SubNivel = apps.get_model("matricula", "SubNivel")
        nivel = Nivel.objects.create(
            order=10,
            name="Amiguinhos de Jesus"
        )
        subnivel = SubNivel.objects.create(
            order=10,
            nivel=nivel,
            name="Amiguinhos I",
            idade=7
        )       
        subnivel = SubNivel.objects.create(
            order=20,
            nivel=nivel,
            name="Amiguinhos II",
            idade=8
        )
        subnivel = SubNivel.objects.create(
            order=30,
            nivel=nivel,
            name="Amiguinhos III",
            idade=9
        )
        subnivel = SubNivel.objects.create(
            order=40,
            nivel=nivel,
            name="Amiguinhos IV",
            idade=10
        )
        nivel = Nivel.objects.create(
            order=20,
            name="Eucaristia"
        )
        subnivel = SubNivel.objects.create(
            order=60,
            nivel=nivel,
            name="Eucaristia I",
            idade=11
        )
        subnivel = SubNivel.objects.create(
            order=70,
            nivel=nivel,
            name="Eucaristia II",
            idade=12
        )
        Nivel.objects.create(
            order=30,
            name="Crisma"
        )
        subnivel = SubNivel.objects.create(
            order=80,
            nivel=nivel,
            name="Crisma I",
            idade=13
        )
        subnivel = SubNivel.objects.create(
            order=90,
            nivel=nivel,
            name="Crisma II",
            idade=14
        )
        subnivel = SubNivel.objects.create(
            order=100,
            nivel=nivel,
            name="Crisma III",
            idade=15
        )
        subnivel = SubNivel.objects.create(
            order=101,
            nivel=nivel,
            name="Adultos",
            idade=16
        )

    dependencies = [
        ('matricula', '0004_alter_proof_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Nível Maior',
                'verbose_name_plural': 'Níveis Maiores',
            },
        ),
        migrations.CreateModel(
            name='SubNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
                ('idade', models.IntegerField(default=0, verbose_name='Idade Mìnima')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.nivel')),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(choices=[('matriz', 'Domingo'), ('miguel', 'São Miguel'), ('pedro', 'São Pedro'), ('bom', 'Bom Jesus'), ('guadalupe', 'Guadalupe')], max_length=300, verbose_name='Local')),
                ('dia', models.CharField(choices=[('domingo', 'Domingo'), ('sábado', 'Sábado')], max_length=300, verbose_name='Dia')),
                ('horario', models.CharField(choices=[('8', '08:00H'), ('15', '15:00H'), ('16', '16:00H'), ('17', '17:00H')], max_length=300, verbose_name='Horário')),
                ('sala', models.IntegerField(default=0, verbose_name='Ordem')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.subnivel')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turma',
            },
        ),
        migrations.CreateModel(
            name='Catequista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nome completo')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.turma')),
            ],
            options={
                'verbose_name': 'Catequista',
                'verbose_name_plural': 'Catequista',
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.turma'),
        ),
        migrations.RunPython(load_data),

    ]
