# Generated by Django 4.0.1 on 2022-03-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_nivel_subnivel_turma_catequista_matricula_turma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['order'], 'verbose_name': 'Nível Maior', 'verbose_name_plural': 'Níveis Maiores'},
        ),
        migrations.AlterModelOptions(
            name='subnivel',
            options={'ordering': ['order'], 'verbose_name': 'Nível', 'verbose_name_plural': 'Níveis'},
        ),
        migrations.AlterField(
            model_name='turma',
            name='local',
            field=models.CharField(choices=[('matriz', 'Matriz'), ('miguel', 'São Miguel'), ('pedro', 'São Pedro'), ('bom', 'Bom Jesus'), ('guadalupe', 'Guadalupe')], max_length=300, verbose_name='Local'),
        ),
    ]
