# Generated by Django 4.0.1 on 2022-03-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0006_alter_nivel_options_alter_subnivel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='dia',
            field=models.CharField(choices=[('domingo', 'Domingo'), ('sabado', 'Sábado')], max_length=300, verbose_name='Dia'),
        ),
    ]
